### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Daroach0** [yhs21241/StarRail-plugin-PanelPic#1]
角色图片加量包安装失败！
Error code: 128
Error: Command failed: git clone https://github.com/yhs21241/StarRail-plugin-PanelPic.git "F:\yunzaiv3\Yunzai-Bot/plugins/StarRail-plugin/resources//pro-file/" --depth=1
Cloning into 'F:\yunzaiv3\Yunzai-Bot/plugins/StarRail-plugin/resources//pro-file'...
fatal: unable to access 'https://github.com/yhs21241/StarRail-plugin-PanelPic.git/': Could not resolve host: github.com

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
 请稍后重试。

**Comment by yhs21241** [comment]
![image](https://github.com/yhs21241/StarRail-plugin-PanelPic/assets/50403738/a284f7a9-4e87-4f12-82f1-ef47f4f6fde9)
你好，请保证自己能稳定链接到github，建议开启VPN，或者  steam++  开启github加速

**Comment by Daroach0** [comment]
开了steam++已经

**Comment by yhs21241** [comment]
> 开了steam++已经

那如果还是链接不上，建议开vpn
